name: GitHub Actions testing the workflow
run-name: ${{ github.actor }} is testing the workflow
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was triggered by a ${{ github.event_name }} event." 

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }} 
      
      # Build Stage 
      - name: npm install
        run: |
            pip install -r requirements.txt 

      # Test Stage
      - name: Run Tests
        run: | 
          ls ${{ github.workspace }}/project
          chmod +x ${{ github.workspace }}/project/tests.sh
          .${{ github.workspace }}/project/tests.sh
